# Generated by Django 4.2.4 on 2023-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carnet',
            field=models.CharField(default='valor_predeterminado', max_length=20),
        ),
    ]
