# Generated by Django 4.2.4 on 2023-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0002_usuario_carnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carnet',
            field=models.CharField(max_length=20),
        ),
    ]
