# Generated by Django 4.2.4 on 2023-10-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0005_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50)),
            ],
        ),
    ]
