# Generated by Django 4.2.4 on 2023-10-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0008_alter_historial_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
