# Generated by Django 4.2.4 on 2023-11-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0009_alter_historial_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='comentario',
            field=models.TextField(blank=True, default='Ningún Comentario', null=True),
        ),
    ]
