# Generated by Django 4.2.4 on 2023-11-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0010_movimiento_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='comentario',
            field=models.TextField(blank=True, default='Ningún Comentario', null=True),
        ),
    ]
