# Generated by Django 4.2.6 on 2023-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0011_historial_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='Ningún modelo', max_length=100),
        ),
    ]
