# Generated by Django 4.2.4 on 2023-11-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0012_producto_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivoFijo', models.CharField(max_length=255)),
                ('Objeto', models.CharField(max_length=255)),
                ('Marca', models.CharField(max_length=255)),
                ('Modelo', models.CharField(max_length=255)),
                ('Ubicacion', models.CharField(max_length=255)),
                ('Utilidad', models.CharField(max_length=255)),
            ],
        ),
    ]
