# Generated by Django 4.2.4 on 2023-11-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0013_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Utilidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
