# Generated by Django 4.2.4 on 2023-11-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0014_alter_inventario_utilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='utilidad',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
