# Generated by Django 4.2.4 on 2023-11-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0015_producto_ubicacion_producto_utilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='Ningún modelo', max_length=255),
        ),
    ]
