# Generated by Django 4.2.7 on 2024-02-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0018_remove_producto_utilidad_producto_otra_ubicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='Utilidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
